default:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 300
  dropout: 0.2
  lr: 1.0e-2
  wd: 0

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: false
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2
  
RHG_10:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2

RHG_3:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2

IMDB_dir_form:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2

IMDB_dir_genre:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2

stream_player:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2

twitter_friend:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  MLP_num_layers: 2
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true

  aggregate: "mean" # ['sum','mean']
  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  deepset_input_norm: true
  GPR: true
  LearnMask: false
  PMA: true # false为AllSetformer
  heads: 1 
  output_heads: 1
  decoder_hidden: 64 # decoder代替的就是原来的classifier
  decoder_num_layers: 2