default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 500
  dropout: 0.2
  lr: 1.0e-3
  wd: 0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

RHG_10:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0.0
  pooling: "max"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN

RHG_3:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0.0
  pooling: "max"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN

IMDB_dir_form:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0.0
  pooling: "mean"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN

IMDB_dir_genre:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0.0
  pooling: "mean"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN

stream_player:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3
  wd: 0.0
  pooling: "mean"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN

twitter_friend:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3
  wd: 0.0
  pooling: "mean"
  early_stop: true

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: false # HyperGCN_fast 为 True 表示 FastHyperGCN