default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 500
  dropout: 0.2
  lr: 1.0e-3
  wd: 0

  HyperGCN_mediators: true
  HyperGCN_fast: true 

RHG_10:
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0.0
  pooling: "max"
  early_stop: true

  HyperGCN_mediators: true 
  HyperGCN_fast: false 
