default:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.2
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

RHG_10:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 300
  dropout: 0.2
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true

RHG_3:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true

IMDB_dir_form:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true

IMDB_dir_genre:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true

stream_player:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true

twitter_friend:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 64
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0
  pooling: "max"
  early_stop: true