default:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3
  wd: 0

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-4
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" 
  aggregate: "mean"   

RHG_10:
  embedding_hidden: 64
  MLP_num_layers: 2
  MLP_hidden: 64
  epochs: 200
  dropout: 0.2
  lr: 1.0e-2
  wd: 0
  pooling: "mean"
  early_stop: true
  hg_batch_size: 128

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.9

  normalization: "ln" 
  aggregate: "mean"   


