default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 500
  dropout: 0.2
  lr: 1.0e-3
  wd: 0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

cora:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 150
  dropout: 0.5
  lr: 1.0e-3
  wd: 0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

pubmed:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 200
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

coauthor_cora:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.8
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

coauthor_dblp:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.8
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

yelp:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 300
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

walmart-trips-100:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

actor:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 400
  dropout: 0.5
  lr: 1.0e-1 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

amazon:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 400
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

twitch:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

pokec:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

german:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

bail:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN

credit:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  HyperGCN_mediators: true # HyperGCN_mediators 为 True 表示 HyperGCN, False 表示 1-HyperGCN
  HyperGCN_fast: true # HyperGCN_fast 为 True 表示 FastHyperGCN