default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 128 # expansion卷积后的维度

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

cora:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

pubmed:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

coauthor_cora:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

coauthor_dblp:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

actor:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

amazon:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

twitch:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 80
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2

pokec:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 2
  atten_neg_slope: 0.2

german:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 20
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 2
  atten_neg_slope: 0.2

bail:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 300
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

  expan_dim: 256 # expansion卷积后的维度

  cg_num_layer: 1
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 # -1表示全部参与attention计算，否则为chunked attention

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 # DFF中的hidden_dim
  dff_num_layers: 1
  atten_neg_slope: 0.2
