default:
  All_num_layers: 1
  embedding_hidden: 128
  epochs: 200
  dropout: 0.2
  lr: 1.0e-3  
  wd: 0

  edconv_type: "EquivSet" 
  MLP_hidden: 128
  MLP_num_layers: 2
  MLP2_num_layers: -1
  MLP3_num_layers: -1
  decoder_hidden: 128
  decoder_num_layer: 1

  aggregate: "mean" # aggregate ['sum', 'mean']

  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  activation: "prelu"
  AllSet_input_norm: true
  alpha: 0.5

cora:
  All_num_layers: 1
  embedding_hidden: 128
  epochs: 500
  dropout: 0.5
  lr: 1.0e-3  
  wd: 0

  edconv_type: "EquivSet" 
  MLP_hidden: 512
  MLP_num_layers: 0
  MLP2_num_layers: 1
  MLP3_num_layers: 1
  decoder_hidden: 256
  decoder_num_layer: 1

  aggregate: "mean" # aggregate ['sum', 'mean']

  normalization: "ln" # NormLayer for MLP. ['bn','ln','None']
  activation: "prelu"
  AllSet_input_norm: true
  alpha: 0.5
