default:
  All_num_layers: 2
  MLP_hidden: 256
  epochs: 50 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.8

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.3
  lamda: 0.8
  reduce: 'mean'

cora:
  All_num_layers: 2
  MLP_hidden: 256
  epochs: 50 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.8

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.3
  lamda: 0.8
  reduce: 'mean'

pubmed:
  All_num_layers: 2
  MLP_hidden: 128
  epochs: 100 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.0

  input_drop: 0.3
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.5
  lamda: 0.5
  reduce: 'mean'

coauthor_cora:
  All_num_layers: 2
  MLP_hidden: 256
  epochs: 50 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.8

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.3
  lamda: 0.8
  reduce: 'mean'

coauthor_dblp:
  All_num_layers: 2
  MLP_hidden: 128
  epochs: 100 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.5

  input_drop: 0.3
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.2
  lamda: 0.3
  reduce: 'mean'

yelp:
  All_num_layers: 2
  MLP_hidden: 128
  epochs: 180 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.2

  input_drop: 0.0
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.8
  lamda: 0.8
  reduce: 'mean'

walmart-trips-100:
  All_num_layers: 2
  MLP_hidden: 128
  epochs: 200 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.5

  input_drop: 0.3
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.0
  lamda: 0.3
  reduce: 'mean'

trivago:
  All_num_layers: 2
  MLP_hidden: 64
  epochs: 1000 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.5

  input_drop: 0.2
  activation: "relu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.0
  lamda: 0.3
  reduce: 'sum'

actor:
  All_num_layers: 1
  MLP_hidden: 256
  epochs: 200 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 1.0
  lamda: 0.5
  reduce: 'mean'

amazon:
  All_num_layers: 1
  MLP_hidden: 128
  epochs: 50 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.1

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.0
  lamda: 0.8
  reduce: 'mean'

twitch:
  All_num_layers: 1
  MLP_hidden: 128
  epochs: 100 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.1

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.0
  lamda: 0.5
  reduce: 'mean'

pokec:
  All_num_layers: 1
  MLP_hidden: 128
  epochs: 100 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.0

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.5
  lamda: 0.5
  reduce: 'mean'

german:
  All_num_layers: 1
  MLP_hidden: 128
  epochs: 200 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: True
  restart_alpha: 1.0
  lamda: 0.5
  reduce: 'mean'

bail:
  All_num_layers: 1
  MLP_hidden: 256
  epochs: 40 
  lr: 1.0e-5
  wd: 0.0001
  dropout: 0.0

  input_drop: 0.0
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.1
  lamda: 0.8
  reduce: 'mean'

credit:
  All_num_layers: 1
  MLP_hidden: 256
  epochs: 100
  lr: 1.0e-3
  wd: 0.0001
  dropout: 0.0

  input_drop: 0.0
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.5
  lamda: 0.8
  reduce: 'mean'

NTU2012:
  All_num_layers: 1
  MLP_hidden: 512
  epochs: 200 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.3
  lamda: 0.1
  reduce: 'mean'

ModelNet40:
  All_num_layers: 1
  MLP_hidden: 512
  epochs: 200 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.3
  lamda: 0.1
  reduce: 'mean'

zoo:
  All_num_layers: 1
  MLP_hidden: 256
  epochs: 200 
  lr: 1.0e-2
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.1
  lamda: 0.1
  reduce: 'mean'

house-committees-100:
  All_num_layers: 2
  MLP_hidden: 128
  epochs: 40 
  lr: 1.0e-3
  wd: 0.0
  dropout: 0.5

  input_drop: 0.5
  activation: "prelu" # activation: ['relu', 'prelu']
  use_norm: False
  restart_alpha: 0.5
  lamda: 0.3
  reduce: 'mean'