default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

cora:
  All_num_layers: 3
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.8
  lr: 1.0e-3 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

pubmed:
  All_num_layers: 3
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.8
  lr: 1.0e-3 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

coauthor_cora:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.8
  lr: 1.0e-3 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

coauthor_dblp:
  All_num_layers: 3
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.8
  lr: 1.0e-3 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

actor:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.8
  lr: 1.0e-2 
  wd: 0.0

  normalization: "ln"
  InputNorm: false

pokec:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.0
  lr: 1.0e-2 
  wd: 0.0

  normalization: "ln"
  InputNorm: false
