default:
  HCHA_symdegnorm: true 
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 
  wd: 0.0

cora:
  HCHA_symdegnorm: true 
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 
  wd: 0.0

