default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.0

  norm_type: 0 # choices=[-1, 0, 1, 2, 3]
  threshold: -5
  init_val: 1
  init_type: 0
  sample_rate: 0.1