default:
  HCHA_symdegnorm: true
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 
  wd: 0.0
  hidden_channels: 32 
  num_layers: 2
  num_heads: 4 
  nb_random_features: 30
  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: true
  pe: HEPEHtEPE
  hefeat: mean

cora:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 128
  epochs: 100
  dropout: 0.5
  lr: 5.0e-3 
  wd: 0.001
  num_heads: 4 
  nb_random_features: 30
  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: true
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: maxmin

pubmed:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 
  wd: 0.001
  num_heads: 4 
  nb_random_features: 30

  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: true
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: maxmin

coauthor_cora:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 256
  epochs: 100
  dropout: 0.5
  lr: 5.0e-3
  wd: 0.001
  num_heads: 4 
  nb_random_features: 30

  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: false
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: maxmin

coauthor_dblp:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 128
  epochs: 100
  dropout: 0.5
  lr: 5.0e-4
  wd: 0.01
  num_heads: 4 
  nb_random_features: 30

  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: false
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: maxmin

actor:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 128
  epochs: 100
  dropout: 0.5
  lr: 5.0e-3
  wd: 0.001
  num_heads: 4 
  nb_random_features: 30

  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: false
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: max

pokec:
  All_num_layers: 2
  embedding_hidden: 128
  hidden_channels: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.01
  num_heads: 4 
  nb_random_features: 30

  use_bn: true
  use_gumbel: true
  use_residual: true
  use_act: true
  use_jk: true
  nb_gumbel_sample: 10
  rb_order: 0
  rb_trans: sigmoid 
  use_edge_loss: false
  pe: HEPEHtEPE
  hefeat: mean

  aggr_mode: maxmin