default:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3
  wd: 0

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-4
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "mean"   # aggregate 的聚合选项为 ['sum', 'mean']

cora:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 50
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 2.0
  HyperND_tol: 1.0e-5
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

pubmed:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 512
  epochs: 300
  dropout: 0.2
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.2

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

coauthor_cora:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 200
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.3

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

coauthor_dblp:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 500
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.3

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

yelp:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 500
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.3

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

walmart-trips-100:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 256
  epochs: 600
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.3

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

actor:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 256
  epochs: 300
  dropout: 0.5
  lr: 1.0e-3
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.8

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

amazon:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 256
  epochs: 300
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.2

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

twitch:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 256
  epochs: 300
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.4

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

pokec:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 256
  epochs: 300
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.6

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

german:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 150
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.0001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

bail:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 400
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']

credit:
  embedding_hidden: 128
  MLP_num_layers: 2
  MLP_hidden: 128
  epochs: 400
  dropout: 0.5
  lr: 1.0e-2
  wd: 0.00001

  HyperND_ord: 1.0
  HyperND_tol: 1.0e-3
  HyperND_steps: 100
  restart_alpha: 0.5

  normalization: "ln" # NormLayer for MLP. ['bn', 'ln', 'None']
  aggregate: "sum"   # aggregate 的聚合选项为 ['sum', 'mean']