default:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

cora:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

pubmed:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

coauthor_cora:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

coauthor_dblp:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

yelp:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 300
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

walmart-trips-100:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

actor:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 400
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

amazon:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

twitch:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 64
  epochs: 200
  dropout: 0.0
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

pokec:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 200
  dropout: 0.0
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0

german:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

bail:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 # 科学计数法表示用浮点数
  wd: 0.0

credit:
  HCHA_symdegnorm: false # 设置为false为HGNN,true为HCHA
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 # 科学计数法表示用浮点数
  wd: 0.0