default:
  All_num_layers: 2
  embedding_hidden: 128
  MLP_hidden: 128
  epochs: 100
  dropout: 0.5
  lr: 1.0e-3 
  wd: 0.0

  expan_dim: 128 

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 
  dff_num_layers: 1
  atten_neg_slope: 0.2

cora:
  All_num_layers: 1
  embedding_hidden: 128
  MLP_hidden: 256
  epochs: 100
  dropout: 0.5
  lr: 1.0e-2 
  wd: 0.0

  expan_dim: 256 

  cg_num_layer: 2
  cg_MLP_hidden: 64
  cg_dropout: 0.5

  hg_num_layer: 2
  hg_MLP_hidden: 64
  hg_dropout: 0.5
  mediator: true

  sg_num_layer: 2
  sg_MLP_hidden: 64
  sg_dropout: 0.5 

  taa_spatial_dim: 64
  taa_spectral_dim: 64
  num_heads: 1
  chunk_size: -1 

  spectral_embed_dim: 64
  fc_dim: 64

  dff_MLP_hidden: 64 
  dff_num_layers: 1
  atten_neg_slope: 0.2

